services:
  - type: web
    name: custom-rag-platform
    env: python
    rootDir: app
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
